### ISSUE TITLE
Including ASLPAw in CDlib

### ISSUE THREAD

**Issue by GiulioRossetti** [fsssosei/ASLPAw#1]
Hi, 
I'm the maintainer of CDlib (https://github.com/GiulioRossetti/cdlib) a python library whose aim is to collect community discovery algorithms developed in python so to provide standard I/O and shared evaluation facilities. 

I've recently come across your repository and I was thinking of including ASLPAw in CDlib (we have already ~50 algorithms): let me know if you agree and, most importantly, what's the proper paper citation for your algorithm to place it in our documentation.

Best,
Giulio

**Comment by fsssosei** [comment]
Ok, I agree.

References: 
Xie J, Szymanski B K, Liu X. [Slpa: Uncovering Overlapping Communities in Social Networks via a Speaker-Listener Interaction Dynamic Process](http://www.cs.rpi.edu/~szymansk/papers/icdm-2011.pdf)[C]. IEEE 11th International Conference on Data Mining Workshops (ICDMW). Ancouver, BC: IEEE, 2011: 344–349.

**Comment by fsssosei** [comment]
> 
> 
> Hi,
> I'm the maintainer of CDlib (https://github.com/GiulioRossetti/cdlib) a python library whose aim is to collect community discovery algorithms developed in python so to provide standard I/O and shared evaluation facilities.
> 
> I've recently come across your repository and I was thinking of including ASLPAw in CDlib (we have already ~50 algorithms): let me know if you agree and, most importantly, what's the proper paper citation for your algorithm to place it in our documentation.
> 
> Best,
> Giulio

Ok, I agree.

References:
Xie J, Szymanski B K, Liu X. [Slpa: Uncovering Overlapping Communities in Social Networks via a Speaker-Listener Interaction Dynamic Process](http://www.cs.rpi.edu/~szymansk/papers/icdm-2011.pdf)[C]. IEEE 11th International Conference on Data Mining Workshops (ICDMW). Ancouver, BC: IEEE, 2011: 344–349.
